### ISSUE TITLE
Previous optical element

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OasysWiser#15]
![image](https://user-images.githubusercontent.com/51963146/81945893-f43b9a00-95fe-11ea-8f10-2b750083c1da.png)

Find a way to display Reference O. E. you're referring to when positioning a new O. E.
This depends on:

* selected Mode

* Orientation

**Comment by aljosahafner** [comment]
First, issue #10 has to be solved!

**Comment by capitanevs** [comment]
Q1: you mean that #10 must be solved because the function that gets the reference optical element may fail, and in this case the field "Reference O.E." should be "Not found", correct?

Q2: Once this exception will be solved, it seems to me that the solution is crystal clear. Right os am I missing something?

**Comment by aljosahafner** [comment]
You're correct...

**Comment by capitanevs** [comment]
Both for Q1 and Q2?

**Comment by aljosahafner** [comment]
Yes, for both...

**Comment by aljosahafner** [comment]
I was working on this today. This will be quite tricky to do in the GUI, as the Wiser beamline only gets built when clicking on `Compute`, so the Reference O. E. technically doesn't exist. We can discuss at some point in the future, I am skipping this at the moment.

**Comment by aljosahafner** [comment]
There is a placeholder now...

![image](https://user-images.githubusercontent.com/51963146/83010499-a4a29880-a018-11ea-8e96-87c39d13885f.png)

**Comment by capitanevs** [comment]
Definitely True. 
This makes us remember that

 We decided to separate field computation and beambline construction+positioning `(BeamlineElements.Append +BeamlineElements.ApplyPositioningDirectives)`, it's time to do the first step. Of course this does not solve the present issue but can help.

Once this is done, I have a question.
Is it possible do "progressively build" the beamline structure (i.e. `BeamlineElements`), without calling yet the positioning directives stuff? I envision something like:

1)drag&drop the new optical element
2)The optical element is initialized(to default values) and appended to the beamline (`BeamlineElements.Append`)
3)The user modifies properties of the OE
       -Here the OE can acces the beamline of which he is the last item, or can anyway call the reference.
       - When the form is closed... we update the OE with a one having the right values. This is difficult for how we did the cod in WofryWise, but I guess that just calling `.__init__(user_values)` should work. Or we use a dummy OE, etc

What do yout think?

**Comment by capitanevs** [comment]
Action:
- it is related to the new structure of do_wiser_computation
- it is "automatically" solved when solved issue #10

**NO ACTION REQUIRED**

**Comment by aljosahafner** [comment]
We put the `do_wiser_beamline` somewhere into the GUI, for example where you select the PD type (distance from source, distance from previous, etc.). This way the beamline will be initialized and the previous element will be picked up by `get_previousOE`...

**Comment by capitanevs** [comment]
Probably since we are late this is simpler for now.
But in the future we should consider the following alternative

**Operation A**
`do_wiser_beamline` is called every time that a OASYS widget is appended/linked to another. It contains:

- init OpticalElement with `CoreOpticsElement=None` => `do_wiser_optical_element`
- `BeamlineElements.Append(...)` => this can be incremental or traverse OASYS chain of responsibility from the beginning every time, if it is simpler. 

**Problems** what happens if the widghet is disconnected? or if distinct "partial chains" are present? (e.g. A-B-C and F-G-H) and I am still drawing the missing dots?)

**Operation B**
- every time that you change/close a widget, you init the CoreOpticsElement and you replace it =>`do_wiser_core_optics_element`


**Operation C**
- refresh_wiser_beamline => RefreshPositioningDirectives. Called via a) menu command, AND  b) before running the computation


**Comments?/ramifications?**
tnx

**Comment by aljosahafner** [comment]
It works in the following way, you click "Beamline" and then the reference element is updated:

![image](https://user-images.githubusercontent.com/51963146/85554832-977fc600-b625-11ea-8048-eeb2d427d077.png)

![image](https://user-images.githubusercontent.com/51963146/85554918-ac5c5980-b625-11ea-88f7-c8e3f371914b.png)

**Comment by aljosahafner** [comment]
The thing which has to be updated still is that when you set:

* `Set fixed distance from source` it always shows the Source

**Comment by aljosahafner** [comment]
Done:
![image](https://user-images.githubusercontent.com/51963146/85558724-525d9300-b629-11ea-8809-1a0a559d222e.png)

![image](https://user-images.githubusercontent.com/51963146/85558771-5c7f9180-b629-11ea-9a26-e8ea49e6a2cf.png)

**Comment by capitanevs** [comment]
Acknowledged.
